config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :items
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:imię, :nazwisko, :numer_telefonu, :adres_email)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[ show edit update destroy ]

  # GET /pets or /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1 or /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:imię, :nazwisko, :age, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/hello/index.html.erb
<div class="App">
  <header class="App-header">
    <img src="Octocat.png" class="App-logo" alt="logo" />
    <p>
      GitHub Coespaces <span class="heart">♥️</span> Rails
    </p>
    <p class="small">
      Edit <code>app/views/hello/index.html.erb</code> and see changes live!
    </p>
  </header>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :imię, style: "display: block" %>
    <%= form.text_field :imię %>
  </div>

  <div>
    <%= form.label :nazwisko, style: "display: block" %>
    <%= form.text_field :nazwisko %>
  </div>

  <div>
    <%= form.label :numer_telefonu, style: "display: block" %>
    <%= form.text_field :numer_telefonu %>
  </div>

  <div>
    <%= form.label :adres_email, style: "display: block" %>
    <%= form.text_field :adres_email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Imię:</strong>
    <%= item.imię %>
  </p>

  <p>
    <strong>Nazwisko:</strong>
    <%= item.nazwisko %>
  </p>

  <p>
    <strong>Numer telefonu:</strong>
    <%= item.numer_telefonu %>
  </p>

  <p>
    <strong>Adres email:</strong>
    <%= item.adres_email %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path, class:"btn btn-success" %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodespacesTryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
  <%= link_to "Home", root_path, class:"btn btn-warning" %>
  <%= link_to "Item", items_path, class:"btn btn-success" %>
  <%= link_to "Pet", pets_path, class:"btn btn-info" %>
    <%= yield %>
    <%= link_to "New pet", new_pet_path, class:"btn btn-info" %>

  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :imię, style: "display: block" %>
    <%= form.text_field :imię %>
  </div>

  <div>
    <%= form.label :nazwisko, style: "display: block" %>
    <%= form.text_field :nazwisko %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.datetime_field :data %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Imię:</strong>
    <%= pet.imię %>
  </p>

  <p>
    <strong>Nazwisko:</strong>
    <%= pet.nazwisko %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= pet.age %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= pet.data %>
  </p>

</div>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Show this pet", @pet %> |
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pets</h1>

<div id="pets">
  <% @pets.each do |pet| %>
    <%= render pet %>
    <p>
      <%= link_to "Show this pet", pet %>
    </p>
  <% end %>
</div>

<%= link_to "New pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet %>

<div>
  <%= link_to "Edit this pet", edit_pet_path(@pet) %> |
  <%= link_to "Back to pets", pets_path %>

  <%= button_to "Destroy this pet", @pet, method: :delete %>
</div>